# Generated by Django 3.0.5 on 2025-04-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(blank=True, max_length=500, null=True)),
                ('symptoms', models.TextField(blank=True, max_length=500, null=True)),
                ('treatment', models.TextField(blank=True, max_length=500, null=True)),
                ('prescription', models.TextField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('tests', models.TextField(blank=True, max_length=500, null=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_records', to='hospital.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='emr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.PatientEMR'),
        ),
    ]
