# Generated by Django 3.0.5 on 2025-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20251028_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenseddrug',
            name='drug',
        ),
        migrations.AddField(
            model_name='dispenseddrug',
            name='drug_name',
            field=models.CharField(default='Unknown Drug', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispenseddrug',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
