# Generated by Django 5.2.7 on 2025-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0022_alter_appointment_id_alter_dispenseddrug_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labresult",
            name="test",
        ),
        migrations.AddField(
            model_name="labresult",
            name="test_name",
            field=models.CharField(default="unknown", max_length=150),
            preserve_default=False,
        ),
    ]
