# Generated by Django 5.2.7 on 2025-11-16 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_labrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='patient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
