# Generated by Django 5.2.7 on 2025-11-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/AccountProfilePic/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/LabProfilePic/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/NurseProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/PharmacyProfilePic/'),
        ),
    ]
