# Generated by Django 5.2.7 on 2025-12-29 15:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_auto_20251127_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabSubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('reference_range', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='remarks',
            new_name='overall_comment',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='result_value',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='test_name',
        ),
        migrations.AddField(
            model_name='labresult',
            name='date_performed',
            field=models.DateField(default=datetime.date(2025, 12, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='test_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='hospital.labresult'),
        ),
        migrations.AddField(
            model_name='labresultvalue',
            name='subtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.labsubtest'),
        ),
        migrations.AddField(
            model_name='labsubtest',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtests', to='hospital.labtestpanel'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.labtestpanel'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.labtestpanel'),
        ),
    ]
