# Generated by Django 5.2.7 on 2026-01-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_remove_billitem_reference_id_billitem_lab_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
