# Generated by Django 5.2.7 on 2026-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0045_add_obstetric_pelvic_scan_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
